/** @type {import('tailwindcss').Config} */

const cv = (name) => `rgb(var(--color-${name}) / <alpha-value>)`;

module.exports = {
  darkMode: 'class',
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "background":                   cv("background"),
        "on-background":                cv("on-background"),
        "surface":                      cv("surface"),
        "surface-bright":               cv("surface-bright"),
        "surface-dim":                  cv("surface-dim"),
        "surface-variant":              cv("surface-variant"),
        "surface-tint":                 cv("surface-tint"),
        "surface-container-lowest":     cv("surface-container-lowest"),
        "surface-container-low":        cv("surface-container-low"),
        "surface-container":            cv("surface-container"),
        "surface-container-high":       cv("surface-container-high"),
        "surface-container-highest":    cv("surface-container-highest"),
        "on-surface":                   cv("on-surface"),
        "on-surface-variant":           cv("on-surface-variant"),
        "inverse-surface":              cv("inverse-surface"),
        "inverse-on-surface":           cv("inverse-on-surface"),
        "outline":                      cv("outline"),
        "outline-variant":              cv("outline-variant"),
        "primary":                      cv("primary"),
        "on-primary":                   cv("on-primary"),
        "primary-container":            cv("primary-container"),
        "on-primary-container":         cv("on-primary-container"),
        "primary-fixed":                cv("primary-fixed"),
        "primary-fixed-dim":            cv("primary-fixed-dim"),
        "on-primary-fixed":             cv("on-primary-fixed"),
        "on-primary-fixed-variant":     cv("on-primary-fixed-variant"),
        "inverse-primary":              cv("inverse-primary"),
        "secondary":                    cv("secondary"),
        "on-secondary":                 cv("on-secondary"),
        "secondary-container":          cv("secondary-container"),
        "on-secondary-container":       cv("on-secondary-container"),
        "secondary-fixed":              cv("secondary-fixed"),
        "secondary-fixed-dim":          cv("secondary-fixed-dim"),
        "on-secondary-fixed":           cv("on-secondary-fixed"),
        "on-secondary-fixed-variant":   cv("on-secondary-fixed-variant"),
        "tertiary":                     cv("tertiary"),
        "on-tertiary":                  cv("on-tertiary"),
        "tertiary-container":           cv("tertiary-container"),
        "on-tertiary-container":        cv("on-tertiary-container"),
        "tertiary-fixed":               cv("tertiary-fixed"),
        "tertiary-fixed-dim":           cv("tertiary-fixed-dim"),
        "on-tertiary-fixed":            cv("on-tertiary-fixed"),
        "on-tertiary-fixed-variant":    cv("on-tertiary-fixed-variant"),
        "error":                        cv("error"),
        "on-error":                     cv("on-error"),
        "error-container":              cv("error-container"),
        "on-error-container":           cv("on-error-container"),
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      fontFamily: {
        "headline": ["var(--font-manrope)", "sans-serif"],
        "body":     ["var(--font-inter)",   "sans-serif"],
        "label":    ["var(--font-inter)",   "sans-serif"],
      },
    },
  },
  plugins: [],
};
